### ISSUE TITLE
No sign-in button on the page

### ISSUE THREAD

**Issue by kandeshvari** [project-zot/zui#384]
**Describe the bug**
There is no sign-in button when the UI is started. In the console, I see an error

```
GET http://localhost:3000/v2/_zot/ext/mgmt 404 (Not Found)
SignIn.jsx:195 TypeError: Cannot read properties of undefined (reading 'data')
    at SignIn.jsx:173:1
```    

**To Reproduce**
Just run `npm start` on the latest version of zot(1.4.3) and zui

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser FireFox 
 - Version 117.0

**Additional context**

my ZOT config

```
distspecversion: 1.0.1-dev
extensions:
  search:
    enable: true
    cve:
      updateInterval: 2h
  sync:
    enable: false
    registries:
    - urls:
      - https://docker.io/library
      content:
      - destination: "/docker.io"
        prefix: "**"
      onDemand: true
      tlsVerify: true
http:
  address: 127.0.0.1
  auth:
    faildelay: 5
    htpasswd:
      path: htpasswd
  port: 8080
  realm: zot
log:
  level: debug
storage:
  rootdirectory: /tmp/zot
```
